# Data Files
training_data_file: bike-sharing-dataset.csv


# Variables
# The variable we are attempting to predict (Survival)
target: cnt

pipeline_name: bikeshare_model
pipeline_save_file: bikeshare__model_output_v

features:      # final features to be use
  - dteday
  - season
  - hr
  - holiday
  - weekday
  - workingday
  - weathersit
  - temp
  - atemp
  - hum
  - windspeed
  - yr
  - mnth
  - casual
  - registered

unused_fields:  # Features to drop before pipeline
  - dteday
  - casual
  - registered

# Features inside processing pipeline

weekday_var: weekday  # first imputatation , then --> Mapping
weathersit_var: weathersit

# gender_var: Sex

# title_var: Title

# age_var: Age 

yr_mappings:
  2011: 0
  2012: 1

mnth_mappings:
  January: 0
  February: 1
  December: 2
  March: 3
  November: 4
  April: 5
  October: 6
  May: 7
  September: 8
  June: 9
  July: 10
  August: 11

season_mappings:
  spring: 0
  winter: 1
  summer: 2
  fall: 3

weather_mappings:
  Heavy Rain: 0
  Light Rain: 1
  Mist: 2
  Clear: 3

holiday_mappings:
  Yes: 0
  No: 1

workingday_mappings:
  No: 0
  Yes: 1

hour_mappings:
  4am: 0
  3am: 1
  5am: 2
  2am: 3
  1am: 4
  12am: 5
  6am: 6
  11pm: 7
  10pm: 8
  10am: 9
  9pm: 10
  11am: 11
  7am: 12
  9am: 13
  8pm: 14
  2pm: 15
  1pm: 16
  12pm: 17
  3pm: 18
  4pm: 19
  7pm: 20
  8am: 21
  6pm: 22
  5pm: 23  

# set train/test split
test_size: 0.20

# to set the random seed
random_state: 42
# alogrithm parameters
# n_estimators: 150
# max_depth: 5
# max_features: 3
